name: Update Swagger
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'test'
jobs:
  update-swagger:
    if: github.repository != 'tmfg/digitraffic-rail'
    environment: ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_SWAGGER_ROLE }}
          role-session-name: gh-actions-update-swagger-rail-${{ github.event.inputs.env }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set environment name
        run: |
          SWAGGER_ENV_NAME=$(echo ${{ github.event.inputs.env }} | awk '{print toupper(substr($0, 1, 1)) substr($0, 2)}')
          echo "SWAGGER_ENV_NAME=$SWAGGER_ENV_NAME" >> $GITHUB_ENV
      - name: Update API Gateway documentation
        run: |
          aws lambda invoke --region ${{ secrets.AWS_REGION }} --function-name SwaggerJoinerRail${{ env.SWAGGER_ENV_NAME }}-UpdateApiDocumentation  update-api-docs-result.json
      - name: Update Swagger documentation
        run: |
          aws lambda invoke --region ${{ secrets.AWS_REGION }} --function-name SwaggerJoinerRail${{ env.SWAGGER_ENV_NAME }}-UpdateSwaggerDescriptions  update-swagger-docs-result.json
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Update Swagger Rail ${{ github.event.inputs.env }}
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
